<!DOCTYPE html>
<html lang="zh-cn">
<head>
<script>
if(!('noModule' in HTMLScriptElement.prototype)){
alert('你的浏览器不能很好的支持 es6，请用最新的chrome、firefox浏览!')
}
const MD_URL='post/ria/js-promise.md';
</script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1" />
<title>JS Promise</title>
<meta name="author" content="ahuigo">
<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css">
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-router@3.0.1/dist/vue-router.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/highlight.js@9.12.0/styles/monokai-sublime.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.css">
<script src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/leancloud-storage@3.10.0/dist/av-min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/valine@1.3.3/dist/Valine.min.js"></script>
</head>
<body class="layout-documentation page-layout">
<div id="app">
<div :id="'imgview'" v-if="imgsrc" @click="imgsrc=null"><div class="popup-back"></div><div class="img-wrapper"><img :src="imgsrc"></div></div>
<div class="pure-menu pure-menu-horizontal">
<div>
<ul class="pure-menu-list">
<li class="pure-menu-item">
<div class="menu-toggle" :class="{a:true}" @click="showMenu=!showMenu">
</div>
</li>
<li class="pure-menu-item"><a href="//github.com/ahuigo">AHUIGO</a></li>
<li class="pure-menu-item"><a class="button is-primary" href="/b">Home</a></li>
<li class="pure-menu-item"><a class="button is-primary" href="//github.com/ahuigo">Github</a></li>
<li class="pure-menu-item"><a class="button is-primary" href="/b/atom.xml">Rss</a></li>
<li class="pure-menu-item"><a class="button is-primary" href="/a#/README.md">Readme</a></li>
<li class="pure-menu-item"><a class="button is-primary" href="/local-jsfiddle/fiddle.html">Fiddle</a></li>
</ul>
</div>
</div>
<div class="main">
<div :class="{left:true, 'active':showMenu}" >
<tree-folder :nodes="nodes" :class="{'active':showMenu}" :show="show"></tree-folder>
</div>
<div class="middle" v-on="showMenu?{click:r=>showMenu=false}:{}">
<router-view></router-view>
<pre id="markdown" v-pre>---
title: JS Promise
date: 2018-10-04
updated: 2019-08-17
---
# 递归promise
Promise 是递归的，Reject 不是

    const onResolved = e =&gt; console.log(&#x27;resolve , &#x27;, e );
    const onRejected = e =&gt; console.log(&#x27;reject , &#x27;, e );

    new Promise( ( resolve , reject ) =&gt; {
        resolve( new Promise( ( resolve , reject ) =&gt; {
            resolve(42);
        } ) );
    } ).then( onResolved , onRejected );

    new Promise( ( resolve , reject ) =&gt; {
        resolve( new Promise( ( resolve , reject ) =&gt; {
            reject(42);
        } ) );
    } ).then( onResolved , onRejected );

    new Promise( ( resolve , reject ) =&gt; {
        reject( new Promise( ( resolve , reject ) =&gt; {
            resolve(42);
        } ) );
    } ).then( onResolved , onRejected );

    new Promise( ( resolve , reject ) =&gt; {
        reject( new Promise( ( resolve , reject ) =&gt; {
            reject(42);
        } ) );
    } ).then( onResolved , onRejected );

# JS Promise
实现异步串行写法
1. generator
1. Promise: resolve-then, reject-catch
2. async-await: 
    1. sync: `result = await promise` 
    2. async: `promise.then(r=&gt;{result=r})`+block

## eventloop
js 是单线程的，通过eventloop 调度，所以回调函数是安全的。

如果想在eventloop 前后插入task，可以通过nextTick/setImmedite:

    log=console.log
    setImmediate(r=&gt;log(&#x27;4.0 setImmediate&#x27;));
    setImmediate(r=&gt;log(&#x27;4.1 setImmediate&#x27;));
    setTimeout(r=&gt;log(&#x27;3. TIMEOUT FIRED&#x27;), 0)
    process.nextTick(r=&gt;log(&#x27;1.1 nextTick&#x27;));
    process.nextTick(r=&gt;log(&#x27;1.2 nextTick&#x27;));

## promise status
执行态和完成态(undefied/rejected/resolved)

    Promise { &lt;pending&gt; }
    Promise { undefined }
    Promise { resolved/resolved }

create instantiated promise

    var promise = Promise.resolve(100);
    var promise = new Promise(r=&gt;r(100));

    new Promise(resolve =&gt; setTimeout(resolve, ms));


## ajax
ajax函数将返回Promise对象:

    function ajax(method, url, data) {
        var request = new XMLHttpRequest();
        return new Promise(function (resolve, reject) {
            request.onreadystatechange = function () {
                if (request.readyState === 4) {
                    if (request.status === 200) {
                        console.log(request.responseText)
                        resolve(request.responseText);
                    } else {
                        reject(request.status);
                    }
                }
            };
            request.open(method, url);
            request.send(data);
        });
    }
    var log = document.getElementById(&#x27;test-promise-ajax-result&#x27;);
    var p = ajax(&#x27;GET&#x27;, &#x27;/api/categories&#x27;); //stop at resolve/reject
    p.then(function (text) { // 如果AJAX成功，获得响应内容
        log.innerText = text;
    }).catch(function (status) { // 如果AJAX失败，获得响应代码
        log.innerText = &#x27;ERROR: &#x27; + status;
    });

## catch
catch 会捕获exception

    (new Promise(()=&gt;{throw new Exception(&#x27;aaaaa&#x27;);})).catch(r=&gt;console.log({r:r}))

then+catch:

    Promise.reject(1).then(
        v=&gt;console.log([v]), 
        e=&gt;console.log(e)
    )

## 串行

    // 5秒后返回input*input的计算结果:
    function multiply(input) {
        return new Promise(function (resolve, reject) {
            log(&#x27;calculating &#x27; + input + &#x27; x &#x27; + input + &#x27;...&#x27;);
            setTimeout(resolve, 5000, input * input);//resolve(input*input)
        });
    }

    // 5秒后返回input+input的计算结果:
    function add(input) {
        return new Promise(function (resolve, reject) {
            log(&#x27;calculating &#x27; + input + &#x27; + &#x27; + input + &#x27;...&#x27;);
            setTimeout(resolve, 5000, input + input);
        });
    }

    var p = new Promise(function (resolve, reject) {
        log(&#x27;start new Promise...&#x27;);
        resolve(123);
    });

    p.then(multiply)
    .then(add)
    .then(multiply)
    .then(add)
    .then(function (result) {
        log(&#x27;Got value: &#x27; + result);
    });

promise.then(f1).then(f2), 对于then/catch 而言： 
1. 如果promise 中没有resolve, promise 正常执行，但是`.then(func)` 永远没有机会执行，
2. f1(),f2() 可以是return promise(就是resolve 返回的参数)，
3. 可以是return value. (value 直接作为参数传递)
4. 但是resolve 不能用于then, 它只能被Promise 包装！Promise 会抛弃return 值

也可以func 返回

    var p = new Promise(function (resolve, reject) {
        console.log(&#x27;start new Promise2...&#x27;);
        resolve(124); //Promise.resolve(124)
    }).then(e=&gt;{return e+1}).
        then(e=&gt;console.log(e)); // second
    console.log({p}); // first 

Another example

    fetch(&#x27;http://localhost:5001&#x27;).then(response=&gt;response.json()).then(json=&gt;{
        this.products=json.products
    })

## 并行
Promise.all()实现如下：

    var p1 = new Promise(function (resolve, reject) {
        saetTimeout(resolve, 500, &#x27;P1&#x27;);
    });
    var p2 = new Promise(function (resolve, reject) {
        setTimeout(resolve, 600, &#x27;P2&#x27;);
    });
    // 同时执行p1和p2，并在它们都完成后执行then:
    Promise.all([p1, p2]).then(function (results) {
        // 获得一个Array: [&#x27;P1&#x27;, &#x27;P2&#x27;]
        console.log(&#x27;results：&#x27;,results); 
    });

如果有多个错误，all.catch 只能捕获一个错误: 

    var p1 = async ()=&gt; {
        console.log(&#x27;p11111&#x27;)
        return &#x27;p1&#x27;; //same as resolve(&#x27;p1&#x27;)
    };
    var error1= async () =&gt;{
        return Promise.reject(&#x27;Error1&#x27;)
    };
    var error2= async () =&gt;{
        throw &#x27;Error2 Value with no trace&#x27;
        throw new Error(&#x27;Error2 Exception&#x27;)
    };
    Promise.all([p1(), error1(),error2()]).then(function (results) {
        console.log(&#x27;results：&#x27;,results); 
    }).catch(e=&gt;console.log({&#x27;error&#x27;:e}));


同时向两个URL读取用户的个人信息，只需要获得先返回的结果即可。这种情况下，用Promise.race()实现：

    var p1 = new Promise(function (resolve, reject) {
        setTimeout(resolve, 500, &#x27;P1&#x27;);
    });
    var p2 = new Promise(function (resolve, reject) {
        setTimeout(resolve, 600, &#x27;P2&#x27;);
    });
    Promise.race([p1, p2]).then(function (result) {
        console.log(result); // &#x27;P1&#x27;
    });

# async-await
## async function is promise
async function 本质就是promise:
1. return 是resolve
1. exception 是reject


## then 包含了await
    fetch(&#x27;/abc&#x27;).then(async (response) =&gt; {
        if(1){return &#x27;result&#x27;}
        throw &#x27;error&#x27;
    }).then(r =&gt; {
        console.log({r});
    }).catch(e =&gt; {
        console.log({error:e});
    })

## await exception
1. 只有 await 可以通过catch 得到exception/reject 的值
2. 没有await 则是： UnhandledPromiseRejectionWarning

await exception

    f2=async ()=&gt;{throw &#x27;error&#x27;}
    f=async ()=&gt;{
        try{
            await f2()
        }catch(e){
            console.log([e])
        }
    }
    f()

## Promise: 捕获try catch

### exception within `new Promise`
promise 中的exception 会被捕获为reject(exception)

    new Promise(()=&gt;{throw new Exception(&#x27;aaaaa&#x27;);}).catch(r=&gt;r).then(r=&gt;console.log([r]))

`new Promise()`比较特别，没有用await 模式， `async(r)` 是一个内promise, 这个内promise没有catch, 报`UnhandledPromiseRejectionWarning`

    new Promise(async()=&gt;{throw new Exception(&#x27;aaaaa&#x27;);}).catch(r=&gt;r).then(r=&gt;console.log([r]))

### promise within non-await async
await reject:

    f = async ()=&gt;{
        //UnhandledPromiseRejectionWarning
        await Promise.reject(1)

        //2
        await Promise.reject(1).catch(r=&gt;r+1)

        //pending
        await new Promise(r=&gt;{})
    }
    f()

## try catch with await
catch err+data

    export function catchEm(promise) {
      return promise.then(data =&gt; [null, data])
        .catch(err =&gt; [err]);
    }

    const [err, data] = await catchEm(asyncFunction(arg1, arg2));


async is used to await promise:

    var p = new Promise(resolve =&gt; {
        setTimeout(() =&gt; resolve(&#x27;resolved&#x27;), 2000);
    });

    async function asyncCall() {
        console.log(&#x27;start&#x27;);
        var result = await p;
        console.log(result); // expected output: &quot;resolved&quot;
        return &#x27;real end!&#x27;;
    }
    asyncCall(); // not &#x27;real end&#x27;, but promise
    console.log(&#x27;not end!&#x27;);

Notice: 
1. 即使没有await, 程序也要等promise 执行完毕才能退出！
2. `await p` 阻塞局部，但是`async` 不会阻塞整体, 所以两者要`成对存在`

await async: 输出2

    async function f(){return 1}
    (
        async ()=&gt;console.log(1+await f())
    )()

## asyncFunc() is promise
1. As promoise support both: then/catch/await
2. AsyncFunc&#x27;s `return` is passed to sub promise&#x27;s `resolve`

e.g.:

    asyncFunc().then(v=&gt;console.log(v));
    v = await asyncFunc().then(v=&gt;(v));// 同步阻塞

1. await/then 只接受`resolve`, catch 只接受`reject`:
    1.  没有resolve, await/then 就不会执行. await 也会阻塞后面的语句. promise 正常执行
    2.  没有reject, catch 则不执行

    var p = new Promise((resolve,reject) =&gt; {
        setTimeout(() =&gt; {
            //resolve(&#x27;abc&#x27;)
            console.log(&#x27;work&#x27;)
        }, 1000);
    });

    async function A(){
        console.log([await p])
        console.log(&#x27;not work&#x27;)
    }
    a=A()
    console.log(a);//pending

    new Promise((resolve,reject) =&gt; {
        setTimeout(e =&gt; console.log(a), 2000); //a 由于await 永远阻塞pending 状态. 
                                                //但是没有timer runing, 不会阻塞程序的退出
    });

# async in then:
## resolve(promise)
resolve 会返回await promise

    new Promise(resolve=&gt;{
        resolve(Promise.resolve(111))
    }).then(console.log)
    //得到111 而不是promise

或这样

    Promise.resolve(3).then(res=&gt;{
        return Promise.resolve(111)
       }).then(res=&gt;console.log([res]))
       //得到是111

## promise in then:
会传promise

    fetch(url).then(async response=&gt;await response.json())

## combine await/then/catch
1. catch 不会向后面的 catch 传导, 但是会向后面的then 传值
2. reject(r)、resolve(r) 不会终止函数，但是第一个r 会被promise 传给 catch/then

example:

    (async function a(){
        var p = new Promise((resolve,reject) =&gt; {
            reject(0)
            console.log(&#x27;----work1--------&#x27;)
            resolve(10)
            console.log(&#x27;----work2--------&#x27;)
        });
        console.log(&#x27;reject:&#x27;, await p.then(e=&gt;e+1).catch(e=&gt;e+3).catch(e=&gt;e+30)); //reject 3
        console.log(&#x27;reject:&#x27;, await p.then(e=&gt;e+1).catch(e=&gt;e+3).then(e=&gt;e+30)); //reject 33(from memory)
        console.log(&#x27;resolve:&#x27;, await Promise.resolve(0).then(e=&gt;e+1).catch(e=&gt;e+3).then(e=&gt;e+30)); //reject 31(from memory)
    })()

result:

    ----work1--------
    ----work2--------
    reject: 3
    reject: 33
    resolve: 31</pre>
<div id="pager"></div>
<div class="hr"></div>
<div class="share" style="display:flex;justify-content:space-between">
<div>
<h4>关注我</h4>
<div>
<iframe width="120" height="22" :src="`https://platform.twitter.com/widgets/follow_button.4a8202e5fcbfb5ba8d36683841f4d020.en.html#screen_name=${config.twitter_user}&width=67&height=22&show_count=false&show_screen_name=true`"></iframe>
<iframe width="120" height="22" :src="`https://widget.weibo.com/relationship/followbutton.php?btn=light&style=1&uid=${config.weibo_uid}&width=67&height=22&language=zh_cn`"></iframe>
</div>
</div>
<div>
<h4>分享文章</h4>
<div>
<span class="icon twitter-icon" @click="openShare('twitter', this)"></span>
<span class="icon weibo-icon" @click="openShare('weibo')"></span>
</div>
</div>
</div>
<div class="hr"></div>
<div id="comments"></div>
</div>
<div class="right">
<div id="toc"><ol><li>笔记</li><ol></div>
<div id="search" class="pure-form">
<fieldset>
<input id="search_q" placeholder="Google" @keyup.enter="searchBlog($('#search_q').value)">
<button @click="searchBlog($('#search_q').value)" class="pure-button pure-button-primary">搜索</button>
</fieldset>
</div>
</div>
</div>
<button class="button is-primary" onclick="window.scroll(0, 10)" id="up">Up</button>
<button class="button is-primary" onclick="window.scrollTo(0,document.body.scrollHeight)" id="down">Down</button>
</div>
<template id="tree-folder">
<ul class="pure-menu-list" v-if="show">
<li class="pure-menu-item" v-for="(file,index) in nodes" :key="file.path">
<a v-if="file.type==='dir'" :type="file.type" @click="openFolder(file)" class="folder">{{file.name}}
</a>
<a v-else :type="file.type" class="file" :href="('/'+file.path).replace(/^\/post\b/, '/b').slice(0,-3)">{{file.name.slice(0,-3)}} </a>
<tree-folder v-if="file.nodes" :show="file.show" :nodes="file.nodes"></tree-folder>
</li>
</ul>
</template>
<template id="md">
<div id="content" v-html="marked(md)"></div>
</template>
<link href="/b/../a/css/main2.css" rel="stylesheet" async>
<script src="/b/js/marked.js"></script>
<script src="/b/js/toc.js"></script>
<script src="/b/../a/js/blog2.js"></script>
</body>
</html>
